# config.py

TELEGRAM_BOT_TOKEN = "8148906065:AAEw8yAPKnhjw3AK2tsYEo-h9LVj74xJS4c"
TELEGRAM_USER_ID = 347552741

# Настройки отслеживания
GROWTH_THRESHOLD_PERCENT = 3.5
TARGET_PROFIT_PERCENT = 5.0
TRACKING_TIMEOUT_HOURS = 12

NOTIFICATION_INTERVAL_SECONDS = 600  # каждые 10 минут
TRACKING_FILE = "tracked_coins.json"

# Кэш RSI/MA
INDICATOR_CACHE_FILE = "indicators_cache.json"
