# crypto_list.py

# Валидные ID монет из Telegram Wallet, проверенные на CoinGecko
TELEGRAM_WALLET_CRYPTOS = [
    "bitcoin",
    "ethereum",
    "toncoin",
    "tether",
    "usd-coin",
    "binancecoin",
    "dogecoin",
    "tron",
    "litecoin",
    "matic-network",
    "wrapped-bitcoin",
    "uniswap",
    "chainlink",
    "bitcoin-cash",
    "stellar",
    "filecoin",
    "arbitrum",
    "apecoin",
    "internet-computer",
    "true-usd",
    "optimism",
    "render-token",
    "the-graph",
    "fantom",
    "axie-infinity",
    "gala",
    "osmosis",
    "mina-protocol",
    "zilliqa",
    "aave",
    "pancakeswap-token",
    "chiliz",
    "1inch",
    "curve-dao-token",
    "compound-governance-token",
    "balancer",
    "yearn-finance",
    "frax-share",
    "ankr",
    "iota",
    "kava",
    "waves",
    "terra-luna",  # Внимание: это не terra-luna-classic (LUNC)
    "neo",
    "celo",
    "qtum",
    "ontology",
    "icon",
    "harmony",
    "band-protocol",
    "sushi"
]
