CRYPTO_LIST = [
    {"id": "bitcoin", "symbol": "BTC", "name": "Bitcoin"},
    {"id": "ethereum", "symbol": "ETH", "name": "Ethereum"},
    {"id": "toncoin", "symbol": "TON", "name": "Toncoin"},
    {"id": "tether", "symbol": "USDT", "name": "Tether"},
    {"id": "binancecoin", "symbol": "BNB", "name": "BNB"},
    {"id": "solana", "symbol": "SOL", "name": "Solana"},
    {"id": "xrp", "symbol": "XRP", "name": "XRP"},
    {"id": "cardano", "symbol": "ADA", "name": "Cardano"},
    {"id": "dogecoin", "symbol": "DOGE", "name": "Dogecoin"},
    {"id": "avalanche-2", "symbol": "AVAX", "name": "Avalanche"},
    {"id": "tron", "symbol": "TRX", "name": "TRON"},
    {"id": "polkadot", "symbol": "DOT", "name": "Polkadot"},
    {"id": "litecoin", "symbol": "LTC", "name": "Litecoin"},
    {"id": "chainlink", "symbol": "LINK", "name": "Chainlink"},
    {"id": "stellar", "symbol": "XLM", "name": "Stellar"},
    {"id": "uniswap", "symbol": "UNI", "name": "Uniswap"},
    {"id": "internet-computer", "symbol": "ICP", "name": "Internet Computer"},
    {"id": "vechain", "symbol": "VET", "name": "VeChain"},
    {"id": "aptos", "symbol": "APT", "name": "Aptos"},
    {"id": "arbitrum", "symbol": "ARB", "name": "Arbitrum"},
    {"id": "optimism", "symbol": "OP", "name": "Optimism"},
    {"id": "near", "symbol": "NEAR", "name": "NEAR Protocol"},
    {"id": "kaspa", "symbol": "KAS", "name": "Kaspa"},
    {"id": "injective-protocol", "symbol": "INJ", "name": "Injective"},
    {"id": "lido-dao", "symbol": "LDO", "name": "Lido DAO"},
    {"id": "mantle", "symbol": "MNT", "name": "Mantle"},
    {"id": "maker", "symbol": "MKR", "name": "Maker"},
    {"id": "sui", "symbol": "SUI", "name": "Sui"},
    {"id": "algorand", "symbol": "ALGO", "name": "Algorand"},
    {"id": "render-token", "symbol": "RNDR", "name": "Render"},
    {"id": "the-graph", "symbol": "GRT", "name": "The Graph"},
    {"id": "axie-infinity", "symbol": "AXS", "name": "Axie Infinity"},
    {"id": "flow", "symbol": "FLOW", "name": "Flow"},
    {"id": "frax-share", "symbol": "FXS", "name": "Frax Share"},
    {"id": "curve-dao-token", "symbol": "CRV", "name": "Curve DAO"},
    {"id": "mina-protocol", "symbol": "MINA", "name": "Mina Protocol"},
    {"id": "1inch", "symbol": "1INCH", "name": "1inch"},
    {"id": "basic-attention-token", "symbol": "BAT", "name": "Basic Attention Token"},
    {"id": "ocean-protocol", "symbol": "OCEAN", "name": "Ocean Protocol"},
    {"id": "origintrail", "symbol": "TRAC", "name": "OriginTrail"},
    {"id": "akash-network", "symbol": "AKT", "name": "Akash Network"},
    {"id": "worldcoin-wld", "symbol": "WLD", "name": "Worldcoin"},
    {"id": "blur", "symbol": "BLUR", "name": "Blur"},
    {"id": "dydx", "symbol": "DYDX", "name": "dYdX"},
    {"id": "galxe", "symbol": "GAL", "name": "Galxe"},
    {"id": "raydium", "symbol": "RAY", "name": "Raydium"},
    {"id": "space-id", "symbol": "ID", "name": "SPACE ID"},
    {"id": "zebec-protocol", "symbol": "ZBC", "name": "Zebec Protocol"},
    {"id": "bonk", "symbol": "BONK", "name": "Bonk"},
    {"id": "dogwifcoin", "symbol": "WIF", "name": "dogwifhat"},
    {"id": "pepe", "symbol": "PEPE", "name": "Pepe"},
    {"id": "floki", "symbol": "FLOKI", "name": "Floki"},
    {"id": "shiba-inu", "symbol": "SHIB", "name": "Shiba Inu"},
]
