CRYPTO_LIST = [
    {"id": "toncoin", "name": "Toncoin"},
    {"id": "tether", "name": "Tether"},
    {"id": "bitcoin", "name": "Bitcoin"},
    {"id": "ethereum", "name": "Ethereum"},
    {"id": "bnb", "name": "BNB"},
    {"id": "solana", "name": "Solana"},
    {"id": "dogecoin", "name": "Dogecoin"},
    {"id": "polygon", "name": "Polygon"},
    {"id": "tron", "name": "TRON"},
    {"id": "aptos", "name": "Aptos"},
    {"id": "optimism", "name": "Optimism"},
    {"id": "arbitrum", "name": "Arbitrum"},
    {"id": "near", "name": "NEAR Protocol"},
    {"id": "stellar", "name": "Stellar"},
    {"id": "monero", "name": "Monero"},
    {"id": "kaspa", "name": "Kaspa"},
    {"id": "hedera-hashgraph", "name": "Hedera"},
    {"id": "algorand", "name": "Algorand"},
    {"id": "elrond-erd-2", "name": "MultiversX"},
    {"id": "mina-protocol", "name": "Mina"},
    {"id": "quant-network", "name": "Quant"},
    {"id": "chainlink", "name": "Chainlink"},
    {"id": "the-graph", "name": "The Graph"},
    {"id": "uniswap", "name": "Uniswap"},
    {"id": "aave", "name": "Aave"},
    {"id": "pancakeswap-token", "name": "PancakeSwap"},
    {"id": "1inch", "name": "1inch"},
    {"id": "sushi", "name": "Sushi"},
    {"id": "curve-dao-token", "name": "Curve DAO"},
    {"id": "terra-luna", "name": "Terra Classic"},
    {"id": "terra-luna-2", "name": "Terra"},
    {"id": "waves", "name": "Waves"},
    {"id": "axie-infinity", "name": "Axie Infinity"},
    {"id": "gala", "name": "Gala"},
    {"id": "filecoin", "name": "Filecoin"},
    {"id": "theta-token", "name": "Theta"},
    {"id": "sandbox", "name": "The Sandbox"},
    {"id": "chiliz", "name": "Chiliz"},
    {"id": "rocket-pool", "name": "Rocket Pool"},
    {"id": "zilliqa", "name": "Zilliqa"},
    {"id": "fetch-ai", "name": "Fetch.ai"},
    {"id": "raydium", "name": "Raydium"},
    {"id": "injective-protocol", "name": "Injective"},
    {"id": "flow", "name": "Flow"},
    {"id": "avalanche-2", "name": "Avalanche"},
    {"id": "polkadot", "name": "Polkadot"},
    {"id": "cardano", "name": "Cardano"},
    {"id": "shiba-inu", "name": "Shiba Inu"},
    {"id": "litecoin", "name": "Litecoin"},
    {"id": "bitcoin-cash", "name": "Bitcoin Cash"},
    {"id": "wrapped-bitcoin", "name": "Wrapped Bitcoin"},
    {"id": "ripple", "name": "XRP"}
]
