[build]
command = "pip install -r requirements.txt && pip install pydantic"

[deploy]
command = "python main.py"

[variables]
TELEGRAM_TOKEN = "8148906065:AAEw8yAPKnhjw3AK2tsYEo-h9LVj74xJS4c"
OWNER_ID = "347552741"
