def get_ton_wallet_tokens():
    return [
        "bitcoin",
        "ethereum",
        "toncoin",
        "tether",
        "binancecoin",
        "usd-coin",
        "tron",
        "polygon",
        "litecoin",
        "solana",
        "dogecoin",
        "avalanche-2",
        "aptos",
        "near",
        "stellar",
        "wrapped-bitcoin",
        "uniswap",
        "chainlink",
        "the-open-network",  # второй идентификатор TON
        "arbitrum",
        "optimism",
        "hedera",
        "injective-protocol",
        "fantom",
        "sui",
        "casper-network",
        "osmosis",
        "render-token",
        "celestia",
        "sei-network",
        "internet-computer"
    ]
